// <auto-generated />
using System;
using BelediyeTicketAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BelediyeTicketAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260723072430_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BelediyeTicketAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bilgi İşlem"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fen İşleri"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mali Hizmetler"
                        },
                        new
                        {
                            Id = 4,
                            Name = "İnsan Kaynakları"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Destek Hizmetleri"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Park ve Bahçeler"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Temizlik İşleri"
                        });
                });

            modelBuilder.Entity("BelediyeTicketAPI.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bilgi İşlem"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fen İşleri"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mali Hizmetler"
                        },
                        new
                        {
                            Id = 4,
                            Name = "İnsan Kaynakları"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Destek Hizmetleri"
                        });
                });

            modelBuilder.Entity("BelediyeTicketAPI.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "HP LaserJet sürekli kağıt sıkıştırıyor.",
                            Status = "Beklemede",
                            Title = "Yazıcı çalışmıyor",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Muhasebe biriminde internet kesildi.",
                            Status = "İşlemde",
                            Title = "İnternet bağlantısı yok",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Başkanlık katındaki klima arızalı.",
                            Status = "Tamamlandı",
                            Title = "Klima çalışmıyor",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("BelediyeTicketAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "ahmet@belediye.com",
                            FirstName = "Ahmet",
                            LastName = "Yılmaz",
                            PasswordHash = "123456",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 3,
                            Email = "ayse@belediye.com",
                            FirstName = "Ayşe",
                            LastName = "Demir",
                            PasswordHash = "123456",
                            Role = "Personel"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 5,
                            Email = "mehmet@belediye.com",
                            FirstName = "Mehmet",
                            LastName = "Kaya",
                            PasswordHash = "123456",
                            Role = "Personel"
                        });
                });

            modelBuilder.Entity("BelediyeTicketAPI.Models.Ticket", b =>
                {
                    b.HasOne("BelediyeTicketAPI.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BelediyeTicketAPI.Models.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BelediyeTicketAPI.Models.User", b =>
                {
                    b.HasOne("BelediyeTicketAPI.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("BelediyeTicketAPI.Models.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BelediyeTicketAPI.Models.User", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
